export const API_PATHS = {
  REGISTER: '/register',
  GET_USER: '/user',
  GOALS: {
    GET: '/goals',
    CREATE_GOAL: '/goals',
    DELETE_GOAL: '/goals',
    UPDATE_GOAL: '/goals',
    UPDATE_SHOW_STATISTIC: '/goals/update-show-statistic',
    UPDATE_CAN_EDIT_PAST: '/goals/update-can-edit-past',
    MARK_ALL_AS_INCOMPLETE: '/goals/mark-all-incomplete',
    UPDATE_DESCRIPTION_SETTINGS: '/goals/update-description-settings',
  },
  CREATE_NEXT_YEAR: '/user/years/create-next',
  UPDATE_USER_NAME: '/user/update-name',
  UPDATE_USER_PASSWORD: '/user/update-password',
  DELETE_USER: '/user',
  ENCRYPT_GOALS: '/user/encrypt',
  DECRYPT_GOALS: '/user/decrypt',
  SECTIONS: {
    GET: '/sections',
    CREATE_SECTION: '/sections',
    DELETE_SECTION: '/sections',
    UPDATE_SECTION: '/sections',
  },
};
