services:
  simple-goals:
    build: .
    container_name: simple-goals-app
    restart: unless-stopped
    ports:
      - 9096:3000
    environment:
      - NEXTAUTH_URL=http://localhost:9096
      - NEXT_TELEMETRY_DISABLED=1
      - NEXTAUTH_SECRET=your_secret_key
      - DATABASE_URL=postgresql://appuser:apppassword@postgres:5432/appdb?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: simple-goals-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - simple-goals-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U appuser -d appdb']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  simple-goals-postgres:
