services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: simple_goals_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
      - '5555:5555'
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysqldata:

networks:
  app-network:
    driver: bridge
