import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

import localFont from 'next/font/local';

import Container from '@/components/ui/container';
import Header from '@/components/ui/header';

import './globals.css';
import { cookies, headers } from 'next/headers';
import { TOKEN } from '@/constants/cookies';
import { USER_ID } from '@/constants/headers';

const jost = localFont({
  src: '../assets/Jost-Regular.woff2',
  variable: '--font-jost',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default async function RootLayout({ children }: Props) {
  const cookiesStore = await cookies();
  const headersStore = await headers();

  const token = cookiesStore.get(TOKEN);
  const userId = headersStore.get(USER_ID);

  const isAuth = !!token && !!userId;

  return (
    <html lang="en">
      <body className={`${jost.className}`}>
        <Toaster />
        <Container>
          <Header isAuth={isAuth} />
          {children}
        </Container>
      </body>
    </html>
  );
}
